package com.example.socceralmanac.models.detail_league

data class DetailLeaguesItem(
	val strDescriptionES: String? = null,
	val dateFirstEvent: String? = null,
	val intFormedYear: String? = null,
	val strBanner: String? = null,
	val strSport: String? = null,
	val strDescriptionIT: String? = null,
	val strDescriptionCN: String? = null,
	val strDescriptionEN: String? = null,
	val strWebsite: String? = null,
	val strYoutube: String? = null,
	val strDescriptionIL: String? = null,
	val idCup: String? = null,
	val strComplete: String? = null,
	val strLocked: String? = null,
	val idLeague: String? = null,
	val idSoccerXML: String? = null,
	val strTrophy: String? = null,
	val strBadge: String? = null,
	val strTwitter: String? = null,
	val strDescriptionHU: String? = null,
	val strGender: String? = null,
	val strLeagueAlternate: String? = null,
	val strDescriptionSE: String? = null,
	val strNaming: String? = null,
	val strDivision: String? = null,
	val strDescriptionJP: String? = null,
	val strFanart1: String? = null,
	val strDescriptionFR: String? = null,
	val strFanart2: String? = null,
	val strFanart3: String? = null,
	val strFacebook: String? = null,
	val strFanart4: String? = null,
	val strCountry: String? = null,
	val strDescriptionNL: String? = null,
	val strRSS: String? = null,
	val strDescriptionRU: String? = null,
	val strDescriptionPT: String? = null,
	val strLogo: String? = null,
	val strDescriptionDE: String? = null,
	val strDescriptionNO: String? = null,
	val strLeague: String? = null,
	val strPoster: String? = null,
	val strDescriptionPL: String? = null
)
